"""Fix relationship typo

Revision ID: c5f821b3322f
Revises: d574efe5fa80
Create Date: 2025-02-13 17:19:18.198569

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c5f821b3322f'
down_revision: Union[str, None] = 'd574efe5fa80'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('llms', sa.Column('created_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('llms', 'created_at')
    # ### end Alembic commands ###
